// Code generated by MockGen. DO NOT EDIT.
// Source: vk_quests/internal/repository/user (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository.go -package=mr -mock_names=Repository=UserRepository . Repository
//

// Package mr is a generated GoMock package.
package mr

import (
	reflect "reflect"
	types "vk_quests/internal/pkg/types"
	quest "vk_quests/internal/repository/quest"
	user "vk_quests/internal/repository/user"

	gomock "go.uber.org/mock/gomock"
)

// UserRepository is a mock of Repository interface.
type UserRepository struct {
	ctrl     *gomock.Controller
	recorder *UserRepositoryMockRecorder
}

// UserRepositoryMockRecorder is the mock recorder for UserRepository.
type UserRepositoryMockRecorder struct {
	mock *UserRepository
}

// NewUserRepository creates a new mock instance.
func NewUserRepository(ctrl *gomock.Controller) *UserRepository {
	mock := &UserRepository{ctrl: ctrl}
	mock.recorder = &UserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserRepository) EXPECT() *UserRepositoryMockRecorder {
	return m.recorder
}

// ApplyCost mocks base method.
func (m *UserRepository) ApplyCost(arg0 *user.User, arg1 *quest.Quest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyCost indicates an expected call of ApplyCost.
func (mr *UserRepositoryMockRecorder) ApplyCost(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCost", reflect.TypeOf((*UserRepository)(nil).ApplyCost), arg0, arg1)
}

// CreateUser mocks base method.
func (m *UserRepository) CreateUser(arg0 *user.User) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *UserRepositoryMockRecorder) CreateUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*UserRepository)(nil).CreateUser), arg0)
}

// DeleteUser mocks base method.
func (m *UserRepository) DeleteUser(arg0 types.Id) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *UserRepositoryMockRecorder) DeleteUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*UserRepository)(nil).DeleteUser), arg0)
}

// GetHistory mocks base method.
func (m *UserRepository) GetHistory(arg0 types.Id) ([]user.HistoryRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", arg0)
	ret0, _ := ret[0].([]user.HistoryRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *UserRepositoryMockRecorder) GetHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*UserRepository)(nil).GetHistory), arg0)
}

// GetUsers mocks base method.
func (m *UserRepository) GetUsers() ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers")
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *UserRepositoryMockRecorder) GetUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*UserRepository)(nil).GetUsers))
}

// HasUser mocks base method.
func (m *UserRepository) HasUser(arg0 types.Id) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HasUser indicates an expected call of HasUser.
func (mr *UserRepositoryMockRecorder) HasUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasUser", reflect.TypeOf((*UserRepository)(nil).HasUser), arg0)
}

// IsCompletedQuest mocks base method.
func (m *UserRepository) IsCompletedQuest(arg0 *user.User, arg1 *quest.Quest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCompletedQuest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsCompletedQuest indicates an expected call of IsCompletedQuest.
func (mr *UserRepositoryMockRecorder) IsCompletedQuest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCompletedQuest", reflect.TypeOf((*UserRepository)(nil).IsCompletedQuest), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *UserRepository) UpdateUser(arg0 *user.User) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *UserRepositoryMockRecorder) UpdateUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*UserRepository)(nil).UpdateUser), arg0)
}
